source "https://rubygems.org"

gem 'lita'
gem 'lita-down-for-everyone'
gem 'lita-eightball'
gem 'lita-excuses'
gem 'lita-forecast'
gem 'lita-google'
gem 'lita-google-images'
gem 'lita-high-five'
gem 'lita-hipchat'
gem 'lita-howdoi'
gem 'lita-retro'
gem 'lita-wikipedia'
gem 'lita-xkcd'
